language: python
python:
- '3.5'
install:
- pip install .
- pip install -r requirements.txt
script: py.test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: GxcSX/fo2yKAb59Tx9Y0CviI5+o03rE0wQXcVtLhAg7x4US+5N8lmdCjQZyDYH0fkiavPF+XlHrw0qpBfg9uJB1XHtIHWprCsOTTg7qtdqcqVmlDTC7kyfp8PHwFF8/rQssgpqMkpbOFzUuLLOA+mCLUfMuQe/j0f1VrQtOXCUf0X+Sgic/rZtvT29InOy2TkQa4X7fNtLfJ2/b/HjhDTWa11H14wyvo5fkFT8JumRM9piq3Cc2nFZwupkdGD3Jrvzdc32wp1clY9D8dEA9dPl+IU+kn8pSRZckUAcOL5bkzi7mU0KEIz9W7n3KrZrqyoQa9YDhHShqXY7tnP6YZvcXfgIYefka5h4Bbgw6vKYoxhR5xmXhznw9ENUSQ8zwUArET4CyHvUHwi+fcPEbXMJTNDfChVr6gFxz7ZifFYKEDIZ62IU4nHX1/OkRHNJiWSTcyqmD9Ldtup6H1MyoJRlbWqfBetEjmfC6+wGbYXD42Q3PdRjGosx8wd8fOeFSyoLyZrisA4WwFQOMnRjj2E9wrvhqngOyOj5nstmwL59ssaY07VaoFkEwYbCWHlI2O1joLQOLSZBCMpsgd0kGCgq4/0UGYkSBne5bozQlfk5f/Qzj3AddabIzZvkuOhIdMUjtBIq2xYdapbdXWiye2E72Rn8MXqM+YxMGxCJpWzQM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/protobackend
  skip_upload_docs: true
